services:
  php-app:
    build: ./php
    image: gestion-produits-php:2.0
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./php/www:/var/www/html
    depends_on:
      - db

  db:
    build: ./database
    image: gestion-produits-mysql:2.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_produits
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
